M48
; DRILL file {KiCad 9.0.7} date 2026-03-06T14:55:03-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-06T14:55:03-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X90.78Y-92.127
X90.78Y-97.907
T2
X102.108Y-55.198
X122.428Y-55.198
T3
X89.814Y-44.145
X89.814Y-109.525
X146.507Y-44.145
M30
